{% block from %}
FROM jolicode/base:latest
{% endblock %}

{% block content %}
{% endblock %}

ENV WORKDIR $HOME/project
ADD . $WORKDIR
WORKDIR ~/project

{% block env %}{% endblock %}

{% block before_install %}{% endblock %}

{% block install %}{% endblock %}

{% block before_script %}{% endblock %}

{% block script %}{% endblock %}