{% extends "Dockerfile.twig" %}

{% block before_install %}
RUN /bin/bash -c -l "cd $WORKDIR{% for line in before_install %} && {{ line|replace({"$": "\$", '"': '\"'}) }}{% endfor %}"
{% endblock %}

{% block install %}
RUN /bin/bash -c -l "cd $WORKDIR{% for line in install %} && {{ line|replace({"$": "\$", '"': '\"'}) }}{% endfor %}"
{% endblock %}

{% block before_script %}
RUN /bin/bash -c -l "cd $WORKDIR{% for line in before_script %} && {{ line|replace({"$": "\$", '"': '\"'}) }}{% endfor %}"
{% endblock %}

{% block script %}
CMD /bin/bash -c -l "cd $WORKDIR{% for line in script %} && {{ line|replace({"$": "\$", '"': '\"'}) }}{% endfor %}"
{% endblock %}